name: SAP Cloud Deployment

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deployment
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to repository
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: lint webapp
        run: npx eslint webapp
      - name: Deploying Project
        uses: integrtr/ui5-deploy@1.1.0
        with:
          type: 'bsp'
          user: ${{ secrets.ABAP_USER }}
          password: ${{ secrets.ABAP_PASSWORD }}
          host: ${{ secrets.ABAP_HOST }}
